-- Create categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  icon text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create profiles table (Providers and Clients)
create table if not exists profiles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  role text not null check (role in ('client', 'provider')),
  name text not null,
  email text,
  avatar_url text,
  location text,
  bio text,
  category_id bigint references categories(id),
  rating numeric default 0,
  reviews_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create reviews table
create table if not exists reviews (
  id bigint generated by default as identity primary key,
  provider_id bigint references profiles(id) not null,
  author_name text not null,
  rating numeric not null,
  text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table categories enable row level security;
alter table profiles enable row level security;
alter table reviews enable row level security;

-- Policies
create policy "Public categories are viewable by everyone" on categories for select to public using (true);
create policy "Public profiles are viewable by everyone" on profiles for select to public using (true);
create policy "Users can update own profile" on profiles for update to authenticated using (auth.uid() = user_id);
create policy "Reviews are viewable by everyone" on reviews for select to public using (true);
create policy "Authenticated users can insert reviews" on reviews for insert to authenticated with check (true);

-- SEED DATA --

-- Insert Categories
insert into categories (name, icon) values
('Reformas', 'construction'),
('Eventos', 'celebration'),
('Aulas', 'school'),
('Limpeza', 'cleaning_services'),
('Elétrica', 'electric_bolt'),
('Beleza', 'brush'),
('Transporte', 'local_shipping'),
('Hidráulica', 'plumbing'),
('Pets', 'pets'),
('Tecnologia', 'devices'),
('Consultoria', 'lightbulb'),
('Saúde', 'health_and_safety'),
('Automotivo', 'directions_car'),
('Jardinagem', 'yard'),
('Gastronomia', 'restaurant'),
('Design', 'palette'),
('Fotografia', 'photo_camera'),
('Música', 'music_note'),
('Mudanças', 'inventory_2')
on conflict (name) do nothing;

-- Insert Providers (Profiles)
-- Note: referencing categories by name subquery
insert into profiles (id, role, name, bio, rating, reviews_count, avatar_url, location, category_id) values
(1, 'provider', 'João da Silva', 'Especialista em instalações residenciais.', 4.8, 120, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlyWj3kv_Ocjr8RaoTdnW_waOhhYhM3tkAhsL7JT_PEItTvP1uXgcmgjadmMFdgqCvkfGK7iW1H7ipUqG_w-bSiv8ml1uIxs7c3NIFZ59ycKPqqk2ZlqxcGKyB5wRTV3egbdVgn50AG1iN8xjqIFftD_9uuH1xZlH1joM8f-e9QujKhkGQ8CH49JVINd1QD45N8Jpk6AulvBNfZWcGnC9KezdVuWNuKb7wwcfjzPFatzMIXRC8hGXpZQ8ZBF2zbKFP0t9BRHIOB8g', 'São Paulo', (select id from categories where name = 'Elétrica')),
(2, 'provider', 'Maria Oliveira', 'Manutenção elétrica comercial e predial.', 4.5, 98, 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7SmU-JkLJObYGLMIXzEwY0MKbAK-EEBZHwdK4T5O-tYyidb0iZ54rEXGM8WL_CV5bRBjAkXVuU_veZ8l6sOTWJ7g_70peaR08Z09Zyncg4NMgd3inxBzNt39Gu_VUMErDHwU37TR_49QZSXOznK6PY8ob72J8-N1I25w9jniPeJyXeTKy8C2J5qfpTsxZ3wLV_UVm8_dg3z76vG4CK1t-ybcmFO2amRAAbTCycxF3c9fWhd7soVUp-PGFbeIxztQG_aJM_IVmX9s', 'Rio de Janeiro', (select id from categories where name = 'Elétrica')),
(3, 'provider', 'Carlos Pereira', 'Reparos urgentes 24 horas.', 4.9, 215, 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4rfJaZvMcmRyUvugUC4H9LnqijN4lNPlBtNWjHiPWyIOP839wkFtNbp0OodZpVnybQAiDPAKp_FYgneh27ZIhmkUe7cDtCJXiKZZCzwQ5JheyvJ5v90xi2BvHZwDBkKAPJUjnnV6BhgDg_kl1f62SBjhn_qgwP3WcEvQrMjaNMmLWGuY3pCAfm8201y4WVfg8zVfzhLIkDS6c7h8-xaqrIB8UQK0_lVWrWO6eZSbvBZUpYUgdVEgM2ziDzdl0p-9YvzC7qkes4BQ', 'São Paulo', (select id from categories where name = 'Elétrica')),
(4, 'provider', 'Ana Costa', 'Projetos de iluminação e automação.', 4.7, 88, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBzObjoApVAnXdbl_qUTMD75J4bTI1yZjVXWYDxk1XpthFbV4ZCiUxzpaBs833DWb1guJHtGDJXjUx3KdXxcFoLc3QfblSji1H5BesGPTeiyTZHNvO3TCoOWe6NqR3bCUewkyu1LKRlJl5dVTNo6ymMs7lZgXnuZeMT3BHIS7kGer09B5jOzMMQeJCr2T5xOcgLa18PooOwULhHsbUOlN1rmiW6DjGQOHFBMZyaDSjDov2rSdUC84Rizte6GKPi92SAHbNhH5kjibE', 'Belo Horizonte', (select id from categories where name = 'Elétrica')),
(5, 'provider', 'Ricardo Lima', 'Sistemas de segurança e CFTV.', 4.6, 75, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqgYFpNGPD8OUoOJcN4HNjbjSkAqYxU0w6x5eP7P89Fv28RrCX6ADiZhgWk7D1CRfnzTvFjj8O7DRzq8R_JgGFNEc1LJunQKAN8K4u-3swpPVOQmwuvq8AD-Eja-_gB-MKApHvA_Q5nUeI_Gw1n8LPx3LcUIvdUskvWpzYfTfA4kAMIQXxmHCgt5diqg1Dx-NOE_gXFKw4pQkqblwSXGGg-pEJ5Ip4A4tCSeeZHepUowyqsXa-Lyb7UGwQ7woOOgSLnI_GExHFI8s', 'Rio de Janeiro', (select id from categories where name = 'Elétrica')),
(6, 'provider', 'Fernanda Alves', 'Atendimento rápido e eficiente.', 5.0, 150, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBlV3aL5rUVBfyOmvGpntqlCw3_nmXpXMl_yM8La9fYYD4FjKHHim_1W31TtQ2GSe1fcOdfeq_A6ypHbKTYF4_mYJYFHNLmZLiMciw_Dnbc0oGtwADucWbU3BWVUcpaeLHHQ_3muvcSQUw5z5KsqWcrVK0cJcce1psyyn0vQ_7vCipYXPRPeQkyELy2MAp0nWDSRBCSHZz5VMjSKtdMmv3mvO5JJUDn7raQeVrHNlHu6hQ2Gw_EahRvYXT3tM78iZPOZ5wB_xNvFnI', 'Curitiba', (select id from categories where name = 'Elétrica')),
(7, 'provider', 'Roberto Souza', 'Pedreiro e pintor com 20 anos de experiência.', 4.9, 310, 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a', 'São Paulo', (select id from categories where name = 'Reformas')),
(8, 'provider', 'Cláudia Martins', 'Limpeza residencial e pós-obra detalhada.', 4.8, 150, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2', 'Rio de Janeiro', (select id from categories where name = 'Limpeza')),
(9, 'provider', 'Marcos Vinícius', 'Suporte técnico, formatação e redes.', 5.0, 45, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d', 'Florianópolis', (select id from categories where name = 'Tecnologia')),
(10, 'provider', 'Patrícia Lima', 'Maquiadora profissional e designer de sobrancelhas.', 4.7, 220, 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5', 'Belo Horizonte', (select id from categories where name = 'Beleza')),
(11, 'provider', 'Lucas Mendes', 'Aulas particulares de Matemática e Física.', 4.9, 80, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e', 'São Paulo', (select id from categories where name = 'Aulas')),
(12, 'provider', 'Juliana Costa', 'Organização de festas, casamentos e buffet.', 4.6, 112, 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604', 'Curitiba', (select id from categories where name = 'Eventos')),
(13, 'provider', 'André Santos', 'Fretes e mudanças para todo o estado.', 4.8, 340, 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae', 'Porto Alegre', (select id from categories where name = 'Transporte')),
(14, 'provider', 'Camila Rocha', 'Dog walker e pet sitter com muito amor.', 5.0, 67, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2', 'Rio de Janeiro', (select id from categories where name = 'Pets')),
(15, 'provider', 'Rafael Nogueira', 'Encanador experiente, caça-vazamentos.', 4.7, 134, 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61', 'Salvador', (select id from categories where name = 'Hidráulica')),
(16, 'provider', 'Beatriz Almeida', 'Consultoria financeira pessoal e empresarial.', 4.9, 55, 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f', 'São Paulo', (select id from categories where name = 'Consultoria')),
(17, 'provider', 'Gustavo Ferreira', 'Pintura residencial e texturas modernas.', 4.8, 99, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', 'Brasília', (select id from categories where name = 'Reformas')),
(18, 'provider', 'Larissa Ribeiro', 'Cabeleireira especialista em cortes e coloração.', 4.9, 210, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80', 'Recife', (select id from categories where name = 'Beleza')),
(19, 'provider', 'Felipe Barbosa', 'Desenvolvimento de sites e aplicativos.', 5.0, 30, 'https://images.unsplash.com/photo-1533227297135-e08819163841', 'São Paulo', (select id from categories where name = 'Tecnologia')),
(20, 'provider', 'Mariana Duarte', 'Professora de Inglês e Espanhol.', 4.8, 140, 'https://images.unsplash.com/photo-1494790108377-be9c29b29330', 'Fortaleza', (select id from categories where name = 'Aulas')),
(21, 'provider', 'Thiago Martins', 'Adestrador comportamental de cães.', 4.9, 180, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7', 'Curitiba', (select id from categories where name = 'Pets'))
on conflict (id) do nothing;
