-- Migration: 20260816_qa_test_infrastructure.sql
-- Description: Infrastructure for QA test accounts, Analytics test-event isolation, and secured QA reset RPC

-- 1. Create qa_test_accounts table to identify test personas safely
CREATE TABLE IF NOT EXISTS public.qa_test_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  persona TEXT NOT NULL CHECK (persona IN ('client', 'provider', 'admin')),
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Index on qa_test_accounts(user_id)
CREATE INDEX IF NOT EXISTS idx_qa_test_accounts_user_id ON public.qa_test_accounts(user_id);

-- Enable RLS on qa_test_accounts
ALTER TABLE public.qa_test_accounts ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Authenticated users and admins view qa_test_accounts" ON public.qa_test_accounts;
CREATE POLICY "Authenticated users and admins view qa_test_accounts"
ON public.qa_test_accounts FOR SELECT
TO authenticated
USING (
  user_id = auth.uid() OR public.is_admin(auth.uid())
);

-- Only admins can insert/update/delete qa_test_accounts
DROP POLICY IF EXISTS "Admins manage qa_test_accounts" ON public.qa_test_accounts;
CREATE POLICY "Admins manage qa_test_accounts"
ON public.qa_test_accounts FOR ALL
TO authenticated
USING (public.is_admin(auth.uid()))
WITH CHECK (public.is_admin(auth.uid()));

-- 2. Add is_test_event column to provider_analytics_events
ALTER TABLE public.provider_analytics_events
ADD COLUMN IF NOT EXISTS is_test_event BOOLEAN NOT NULL DEFAULT false;

-- Performance index for filtering non-test events
CREATE INDEX IF NOT EXISTS idx_analytics_is_test_event 
ON public.provider_analytics_events(provider_id, is_test_event, created_at);

-- 3. Update log_analytics_event RPC to mark events from test accounts
CREATE OR REPLACE FUNCTION public.log_analytics_event(
  p_provider_id BIGINT DEFAULT NULL,
  p_event_type TEXT DEFAULT 'profile_view',
  p_search_term TEXT DEFAULT NULL,
  p_channel TEXT DEFAULT NULL,
  p_portfolio_item_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_owner_user_id UUID;
  v_current_user_id UUID;
  v_is_test_account BOOLEAN := false;
BEGIN
  v_current_user_id := auth.uid();

  -- Check if current user is a registered QA test account
  IF v_current_user_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.qa_test_accounts WHERE user_id = v_current_user_id
    ) INTO v_is_test_account;
  END IF;

  -- Also check if target provider belongs to a QA test account
  IF p_provider_id IS NOT NULL AND NOT v_is_test_account THEN
    SELECT EXISTS (
      SELECT 1 FROM public.provider_profiles pp
      JOIN public.profiles p ON p.id = pp.profile_id
      JOIN public.qa_test_accounts q ON q.user_id = p.user_id
      WHERE pp.id = p_provider_id
    ) INTO v_is_test_account;
  END IF;

  -- Filter owner self-views (P13 rule)
  IF p_provider_id IS NOT NULL AND v_current_user_id IS NOT NULL THEN
    SELECT p.user_id INTO v_owner_user_id
    FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = p_provider_id;

    IF v_owner_user_id IS NOT NULL AND v_owner_user_id = v_current_user_id THEN
      RETURN jsonb_build_object('success', true, 'ignored', true, 'reason', 'owner_self_view');
    END IF;
  END IF;

  -- Insert aggregate analytics event
  INSERT INTO public.provider_analytics_events (
    provider_id,
    event_type,
    search_term,
    channel,
    portfolio_item_id,
    is_test_event,
    created_at
  )
  VALUES (
    p_provider_id,
    p_event_type,
    NULLIF(trim(p_search_term), ''),
    NULLIF(trim(p_channel), ''),
    p_portfolio_item_id,
    v_is_test_account,
    timezone('utc'::text, now())
  );

  RETURN jsonb_build_object('success', true, 'isTestEvent', v_is_test_account);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;

-- 4. SECURED QA RESET RPC (reset_qa_test_provider)
-- Allows admins to reset ONLY registered QA test provider profiles back to draft status
CREATE OR REPLACE FUNCTION public.reset_qa_test_provider(p_provider_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_is_test_provider BOOLEAN := false;
  v_provider_exists BOOLEAN := false;
BEGIN
  -- 1. Check admin privileges
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso negado: privilégios administrativos necessários para executar o reset de QA.';
  END IF;

  -- 2. Verify provider existence
  SELECT EXISTS (
    SELECT 1 FROM public.provider_profiles WHERE id = p_provider_id
  ) INTO v_provider_exists;

  IF NOT v_provider_exists THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_found', 'message', 'Prestador de serviço não encontrado.');
  END IF;

  -- 3. Verify provider belongs strictly to a QA test account in qa_test_accounts
  SELECT EXISTS (
    SELECT 1 FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    JOIN public.qa_test_accounts q ON q.user_id = p.user_id
    WHERE pp.id = p_provider_id
  ) INTO v_is_test_provider;

  IF NOT v_is_test_provider THEN
    RAISE EXCEPTION 'Operação bloqueada: Apenas contas identificadas na infraestrutura de QA podem ser resetadas. Perfis reais não podem ser atingidos.';
  END IF;

  -- 4. Execute cleanup on test provider data
  DELETE FROM public.portfolio_items WHERE provider_id = p_provider_id;
  DELETE FROM public.provider_services WHERE provider_id = p_provider_id;
  DELETE FROM public.service_areas WHERE provider_id = p_provider_id;
  DELETE FROM public.social_links WHERE provider_id = p_provider_id;
  DELETE FROM public.provider_subscriptions WHERE provider_id = p_provider_id;
  DELETE FROM public.provider_status_history WHERE provider_id = p_provider_id;
  DELETE FROM public.provider_analytics_events WHERE provider_id = p_provider_id;

  -- 5. Reset provider_profile status to draft
  UPDATE public.provider_profiles
  SET
    status = 'draft',
    rejection_reason = NULL,
    professional_title = 'Eletricista Residencial — TESTE',
    bio = 'Perfil profissional de testes automatizados do ambiente de QA do Serviços Já.',
    location_city = 'Itapira',
    location_state = 'SP',
    updated_at = timezone('utc'::text, now())
  WHERE id = p_provider_id;

  RETURN jsonb_build_object('success', true, 'message', 'Perfil de teste resetado com sucesso para o estado draft.');
END;
$$;
