-- Migration: 20260815_admin_moderation.sql
-- Description: Admin role support, admin_users table, security functions, trigger-based history auditing, and administrative RPC actions

-- 1. Update profiles role check constraint to include 'admin'
ALTER TABLE public.profiles
DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles
ADD CONSTRAINT profiles_role_check CHECK (role IN ('client', 'provider', 'admin'));

-- 2. Create admin_users table for explicit admin authorization
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Index on admin_users(user_id)
CREATE INDEX IF NOT EXISTS idx_admin_users_user_id ON public.admin_users(user_id);

-- Enable RLS on admin_users
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view admin_users" ON public.admin_users;
CREATE POLICY "Admins can view admin_users"
ON public.admin_users FOR SELECT
TO authenticated
USING (
  user_id = auth.uid() OR
  EXISTS (SELECT 1 FROM public.profiles WHERE user_id = auth.uid() AND role = 'admin')
);

-- 3. Security Definer Helper Function: is_admin(p_user_id)
CREATE OR REPLACE FUNCTION public.is_admin(p_user_id UUID DEFAULT auth.uid())
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF p_user_id IS NULL THEN
    RETURN FALSE;
  END IF;

  RETURN EXISTS (
    SELECT 1 FROM public.admin_users WHERE user_id = p_user_id
  ) OR EXISTS (
    SELECT 1 FROM public.profiles WHERE user_id = p_user_id AND role = 'admin'
  );
END;
$$;

-- 4. Trigger Function for Automatic, Server-Side Status History Logging
CREATE OR REPLACE FUNCTION public.log_provider_status_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF (OLD.status IS DISTINCT FROM NEW.status) THEN
    INSERT INTO public.provider_status_history (
      provider_id,
      from_status,
      to_status,
      changed_by,
      rejection_reason,
      created_at
    )
    VALUES (
      NEW.id,
      COALESCE(OLD.status, 'draft'),
      NEW.status,
      auth.uid(),
      NEW.rejection_reason,
      timezone('utc'::text, now())
    );
  END IF;
  RETURN NEW;
END;
$$;

-- Bind trigger to provider_profiles
DROP TRIGGER IF EXISTS trg_provider_status_history ON public.provider_profiles;
CREATE TRIGGER trg_provider_status_history
  AFTER UPDATE OF status ON public.provider_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.log_provider_status_change();

-- 5. Revoke direct INSERT on provider_status_history for regular users to prevent spoofing
DROP POLICY IF EXISTS "Providers insert status history" ON public.provider_status_history;

-- Only Allow SELECT on provider_status_history for owner or admin
DROP POLICY IF EXISTS "Providers and Admins view status history" ON public.provider_status_history;
CREATE POLICY "Providers and Admins view status history"
ON public.provider_status_history FOR SELECT
TO authenticated
USING (
  public.is_admin(auth.uid()) OR
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = public.provider_status_history.provider_id
    AND p.user_id = auth.uid()
  )
);

-- 6. RPC: admin_approve_provider
CREATE OR REPLACE FUNCTION public.admin_approve_provider(p_provider_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_status TEXT;
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso negado: privilégios administrativos necessários.';
  END IF;

  SELECT status INTO v_current_status
  FROM public.provider_profiles
  WHERE id = p_provider_id;

  IF v_current_status IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_found', 'message', 'Prestador não encontrado.');
  END IF;

  UPDATE public.provider_profiles
  SET
    status = 'published',
    rejection_reason = NULL,
    updated_at = timezone('utc'::text, now())
  WHERE id = p_provider_id;

  RETURN jsonb_build_object('success', true, 'newStatus', 'published');
END;
$$;

-- 7. RPC: admin_reject_provider
CREATE OR REPLACE FUNCTION public.admin_reject_provider(p_provider_id BIGINT, p_reason TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_status TEXT;
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso negado: privilégios administrativos necessários.';
  END IF;

  IF p_reason IS NULL OR trim(p_reason) = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'missing_reason', 'message', 'Por favor, informe o motivo da recusa.');
  END IF;

  SELECT status INTO v_current_status
  FROM public.provider_profiles
  WHERE id = p_provider_id;

  IF v_current_status IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_found', 'message', 'Prestador não encontrado.');
  END IF;

  UPDATE public.provider_profiles
  SET
    status = 'rejected',
    rejection_reason = trim(p_reason),
    updated_at = timezone('utc'::text, now())
  WHERE id = p_provider_id;

  RETURN jsonb_build_object('success', true, 'newStatus', 'rejected');
END;
$$;

-- 8. RPC: admin_suspend_provider
CREATE OR REPLACE FUNCTION public.admin_suspend_provider(p_provider_id BIGINT, p_reason TEXT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_status TEXT;
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Acesso negado: privilégios administrativos necessários.';
  END IF;

  SELECT status INTO v_current_status
  FROM public.provider_profiles
  WHERE id = p_provider_id;

  IF v_current_status IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'not_found', 'message', 'Prestador não encontrado.');
  END IF;

  UPDATE public.provider_profiles
  SET
    status = 'suspended',
    rejection_reason = p_reason,
    updated_at = timezone('utc'::text, now())
  WHERE id = p_provider_id;

  RETURN jsonb_build_object('success', true, 'newStatus', 'suspended');
END;
$$;

-- 9. Allow Admins to View All provider_profiles for Moderation
DROP POLICY IF EXISTS "Admins can view all provider_profiles" ON public.provider_profiles;
CREATE POLICY "Admins can view all provider_profiles"
ON public.provider_profiles FOR SELECT
TO authenticated
USING (
  public.is_admin(auth.uid()) OR
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = public.provider_profiles.profile_id
    AND p.user_id = auth.uid()
  ) OR
  status = 'published'
);
