-- Migration: 20260815_catalog_foundation.sql
-- Description: Catalog foundation database model for Serviços Já

-- 1. PROFILES TABLE (Common user profile)
CREATE TABLE IF NOT EXISTS public.profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('client', 'provider')),
  name TEXT NOT NULL,
  email TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. PROVIDER PROFILES TABLE (Professional information)
CREATE TABLE IF NOT EXISTS public.provider_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  professional_title TEXT,
  bio TEXT,
  experience_years INTEGER CHECK (experience_years >= 0),
  phone TEXT,
  whatsapp TEXT,
  location_city TEXT,
  location_state TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending_review', 'published', 'suspended', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  icon TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. SERVICES TABLE
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. PROVIDER SERVICES TABLE (N:N relationship)
CREATE TABLE IF NOT EXISTS public.provider_services (
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  service_id BIGINT NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (provider_id, service_id)
);

-- 6. PORTFOLIO ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.portfolio_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 7. SOCIAL LINKS TABLE
CREATE TABLE IF NOT EXISTS public.social_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 8. SERVICE AREAS TABLE
CREATE TABLE IF NOT EXISTS public.service_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  author_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating NUMERIC NOT NULL CHECK (rating >= 1 AND rating <= 5),
  text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

CREATE INDEX IF NOT EXISTS idx_provider_profiles_profile_id ON public.provider_profiles(profile_id);
CREATE INDEX IF NOT EXISTS idx_provider_profiles_status ON public.provider_profiles(status);

CREATE INDEX IF NOT EXISTS idx_categories_slug ON public.categories(slug);

CREATE INDEX IF NOT EXISTS idx_services_category_id ON public.services(category_id);
CREATE INDEX IF NOT EXISTS idx_services_slug ON public.services(slug);

CREATE INDEX IF NOT EXISTS idx_provider_services_provider_id ON public.provider_services(provider_id);
CREATE INDEX IF NOT EXISTS idx_provider_services_service_id ON public.provider_services(service_id);

CREATE INDEX IF NOT EXISTS idx_portfolio_items_provider_id ON public.portfolio_items(provider_id);

CREATE INDEX IF NOT EXISTS idx_social_links_provider_id ON public.social_links(provider_id);

CREATE INDEX IF NOT EXISTS idx_service_areas_provider_id ON public.service_areas(provider_id);

CREATE INDEX IF NOT EXISTS idx_reviews_provider_id ON public.reviews(provider_id);
CREATE INDEX IF NOT EXISTS idx_reviews_author_user_id ON public.reviews(author_user_id);

-- ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- RLS POLICIES

-- Categories: Public SELECT for everyone
CREATE POLICY "Public categories select" ON public.categories FOR SELECT TO public USING (true);

-- Services: Public SELECT for active services
CREATE POLICY "Public active services select" ON public.services FOR SELECT TO public USING (active = true);

-- Profiles:
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users insert own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Public view published profiles" ON public.profiles FOR SELECT TO public USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    WHERE pp.profile_id = public.profiles.id AND pp.status = 'published'
  )
);

-- Provider Profiles:
CREATE POLICY "Public view published provider profiles" ON public.provider_profiles FOR SELECT TO public USING (status = 'published');
CREATE POLICY "Providers manage own provider profile" ON public.provider_profiles FOR ALL TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.profiles p 
    WHERE p.id = public.provider_profiles.profile_id AND p.user_id = auth.uid()
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles p 
    WHERE p.id = public.provider_profiles.profile_id AND p.user_id = auth.uid()
  )
);

-- Provider Services:
CREATE POLICY "Public view published provider services" ON public.provider_services FOR SELECT TO public USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    WHERE pp.id = public.provider_services.provider_id AND pp.status = 'published'
  )
);
CREATE POLICY "Providers manage own services" ON public.provider_services FOR ALL TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.provider_services.provider_id AND p.user_id = auth.uid()
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.provider_services.provider_id AND p.user_id = auth.uid()
  )
);

-- Portfolio Items:
CREATE POLICY "Public view published portfolio items" ON public.portfolio_items FOR SELECT TO public USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    WHERE pp.id = public.portfolio_items.provider_id AND pp.status = 'published'
  )
);
CREATE POLICY "Providers manage own portfolio" ON public.portfolio_items FOR ALL TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.portfolio_items.provider_id AND p.user_id = auth.uid()
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.portfolio_items.provider_id AND p.user_id = auth.uid()
  )
);

-- Social Links:
CREATE POLICY "Public view published social links" ON public.social_links FOR SELECT TO public USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    WHERE pp.id = public.social_links.provider_id AND pp.status = 'published'
  )
);
CREATE POLICY "Providers manage own social links" ON public.social_links FOR ALL TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.social_links.provider_id AND p.user_id = auth.uid()
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.social_links.provider_id AND p.user_id = auth.uid()
  )
);

-- Service Areas:
CREATE POLICY "Public view published service areas" ON public.service_areas FOR SELECT TO public USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    WHERE pp.id = public.service_areas.provider_id AND pp.status = 'published'
  )
);
CREATE POLICY "Providers manage own service areas" ON public.service_areas FOR ALL TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.service_areas.provider_id AND p.user_id = auth.uid()
  )
) WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    JOIN public.profiles p ON p.id = pp.profile_id 
    WHERE pp.id = public.service_areas.provider_id AND p.user_id = auth.uid()
  )
);

-- Reviews:
CREATE POLICY "Public view published reviews" ON public.reviews FOR SELECT TO public USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp 
    WHERE pp.id = public.reviews.provider_id AND pp.status = 'published'
  )
);
CREATE POLICY "Authenticated users insert reviews" ON public.reviews FOR INSERT TO authenticated WITH CHECK (author_user_id = auth.uid());
CREATE POLICY "Users update own reviews" ON public.reviews FOR UPDATE TO authenticated USING (author_user_id = auth.uid()) WITH CHECK (author_user_id = auth.uid());
CREATE POLICY "Users delete own reviews" ON public.reviews FOR DELETE TO authenticated USING (author_user_id = auth.uid());

-- SEED CATEGORIES (19 items)
INSERT INTO public.categories (name, icon, slug) VALUES
  ('Reformas', 'construction', 'reformas'),
  ('Eventos', 'celebration', 'eventos'),
  ('Aulas', 'school', 'aulas'),
  ('Limpeza', 'cleaning_services', 'limpeza'),
  ('Elétrica', 'electric_bolt', 'eletrica'),
  ('Beleza', 'brush', 'beleza'),
  ('Transporte', 'local_shipping', 'transporte'),
  ('Hidráulica', 'plumbing', 'hidraulica'),
  ('Pets', 'pets', 'pets'),
  ('Tecnologia', 'devices', 'tecnologia'),
  ('Consultoria', 'lightbulb', 'consultoria'),
  ('Saúde', 'health_and_safety', 'saude'),
  ('Automotivo', 'directions_car', 'automotivo'),
  ('Jardinagem', 'yard', 'jardinagem'),
  ('Gastronomia', 'restaurant', 'gastronomia'),
  ('Design', 'palette', 'design'),
  ('Fotografia', 'photo_camera', 'fotografia'),
  ('Música', 'music_note', 'musica'),
  ('Mudanças', 'inventory_2', 'mudancas')
ON CONFLICT (slug) DO UPDATE SET 
  name = EXCLUDED.name,
  icon = EXCLUDED.icon;

-- SEED SERVICES
INSERT INTO public.services (category_id, name, slug, description, active) VALUES
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Instalação Elétrica', 'instalacao-eletrica', 'Instalações elétricas residenciais e comerciais', true),
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Manutenção Elétrica', 'manutencao-eletrica', 'Reparos e manutenções em redes elétricas', true),
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Instalação de Chuveiro', 'instalacao-chuveiro', 'Instalação e troca de chuveiros elétricos', true),
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Troca de Tomadas', 'troca-tomadas', 'Substituição e instalação de tomadas e interruptores', true),
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Quadros de Energia', 'quadros-energia', 'Montagem e manutenção de quadros de distribuição', true),
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Iluminação LED', 'iluminacao-led', 'Projetos e instalação de iluminação LED', true),
  ((SELECT id FROM public.categories WHERE slug = 'eletrica'), 'Automação Residencial', 'automacao-residencial', 'Instalação de sistemas inteligentes de automação', true),

  ((SELECT id FROM public.categories WHERE slug = 'reformas'), 'Pintura Residencial', 'pintura-residencial', 'Pintura de paredes internas e externas', true),
  ((SELECT id FROM public.categories WHERE slug = 'reformas'), 'Pintura Comercial', 'pintura-comercial', 'Pintura e acabamentos em estabelecimentos comerciais', true),
  ((SELECT id FROM public.categories WHERE slug = 'reformas'), 'Serviços de Pedreiro', 'servicos-pedreiro', 'Alvenaria, pisos, revestimentos e pequenas obras', true),
  ((SELECT id FROM public.categories WHERE slug = 'reformas'), 'Reformas Gerais', 'reformas-gerais', 'Gerenciamento e execução de reformas completas', true),

  ((SELECT id FROM public.categories WHERE slug = 'hidraulica'), 'Manutenção Hidráulica', 'manutencao-hidraulica', 'Reparos em canos, torneiras e vasos sanitários', true),
  ((SELECT id FROM public.categories WHERE slug = 'hidraulica'), 'Caça-Vazamentos', 'caca-vazamentos', 'Detecção e reparo de vazamentos ocultos', true),
  ((SELECT id FROM public.categories WHERE slug = 'hidraulica'), 'Instalação Hidráulica', 'instalacao-hidraulica', 'Montagem de tubulações e redes de água e esgoto', true),

  ((SELECT id FROM public.categories WHERE slug = 'tecnologia'), 'Manutenção de Computadores', 'manutencao-computadores', 'Formatação, limpeza e reparos em PCs e notebooks', true),
  ((SELECT id FROM public.categories WHERE slug = 'tecnologia'), 'Suporte de Redes', 'suporte-redes', 'Configuração de Wi-Fi, roteadores e redes locais', true),
  ((SELECT id FROM public.categories WHERE slug = 'tecnologia'), 'Desenvolvimento de Sites', 'desenvolvimento-sites', 'Criação de páginas web e portais institucionais', true),
  ((SELECT id FROM public.categories WHERE slug = 'tecnologia'), 'Desenvolvimento de Aplicativos', 'desenvolvimento-aplicativos', 'Criação de aplicativos para iOS e Android', true),

  ((SELECT id FROM public.categories WHERE slug = 'limpeza'), 'Limpeza Residencial', 'limpeza-residencial', 'Serviços de faxina e conservação para casas e apartamentos', true),
  ((SELECT id FROM public.categories WHERE slug = 'limpeza'), 'Limpeza Pós-Obra', 'limpeza-pos-obra', 'Higienização detalhada após reformas ou construções', true),
  ((SELECT id FROM public.categories WHERE slug = 'limpeza'), 'Limpeza Comercial', 'limpeza-comercial', 'Limpeza e organização de escritórios e lojas', true)
ON CONFLICT (slug) DO UPDATE SET 
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  active = EXCLUDED.active;
