-- Migration: 20260815_subscriptions_foundation.sql
-- Description: Create subscription_plans, provider_subscriptions tables, RLS policies, and seed plans

-- 1. Create subscription_plans table
CREATE TABLE IF NOT EXISTS public.subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  billing_interval TEXT NOT NULL DEFAULT 'month',
  billing_interval_count INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Create provider_subscriptions table
CREATE TABLE IF NOT EXISTS public.provider_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  plan_id BIGINT NOT NULL REFERENCES public.subscription_plans(id),
  status TEXT NOT NULL CHECK (status IN ('pending', 'active', 'past_due', 'cancelled', 'expired')),
  started_at TIMESTAMPTZ,
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  gateway TEXT,
  gateway_customer_id TEXT,
  gateway_subscription_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Partial Unique Index: Only 1 active or pending subscription per provider at a time
CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_active_sub 
ON public.provider_subscriptions(provider_id) 
WHERE status IN ('pending', 'active');

-- Index on provider_id for fast queries
CREATE INDEX IF NOT EXISTS idx_provider_subscriptions_provider_id 
ON public.provider_subscriptions(provider_id);

-- 3. Enable RLS
ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_subscriptions ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for subscription_plans
DROP POLICY IF EXISTS "Public view active subscription plans" ON public.subscription_plans;

CREATE POLICY "Public view active subscription plans"
ON public.subscription_plans FOR SELECT
TO public
USING (is_active = true);

-- 5. RLS Policies for provider_subscriptions
DROP POLICY IF EXISTS "Providers view own subscriptions" ON public.provider_subscriptions;
DROP POLICY IF EXISTS "Providers insert pending subscription" ON public.provider_subscriptions;

-- Providers can view ONLY their own subscriptions
CREATE POLICY "Providers view own subscriptions"
ON public.provider_subscriptions FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = public.provider_subscriptions.provider_id
    AND p.user_id = auth.uid()
  )
);

-- Providers can insert ONLY 'pending' subscriptions for their own provider profile
CREATE POLICY "Providers insert pending subscription"
ON public.provider_subscriptions FOR INSERT
TO authenticated
WITH CHECK (
  status = 'pending' AND
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = public.provider_subscriptions.provider_id
    AND p.user_id = auth.uid()
  )
);

-- 6. Idempotent Seed Data for Commercial Plans
INSERT INTO public.subscription_plans (name, slug, description, price, billing_interval, billing_interval_count, is_active, sort_order)
VALUES
  (
    'Mensal',
    'monthly',
    'Plano mensal com cobrança a cada 30 dias. Ideal para quem deseja flexibilidade.',
    19.90,
    'month',
    1,
    true,
    1
  ),
  (
    'Trimestral',
    'quarterly',
    'Plano trimestral com cobrança a cada 3 meses (R$ 50,70 no ciclo - equivalente a R$ 16,90/mês).',
    50.70,
    'month',
    3,
    true,
    2
  ),
  (
    'Anual',
    'annual',
    'Plano anual com cobrança a cada 12 meses (R$ 178,80 no ciclo - equivalente a R$ 14,90/mês). Maior economia.',
    178.80,
    'month',
    12,
    true,
    3
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  billing_interval = EXCLUDED.billing_interval,
  billing_interval_count = EXCLUDED.billing_interval_count,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_at = timezone('utc'::text, now());
