-- Migration: 20260815_provider_lifecycle.sql
-- Description: Provider profile lifecycle, rejection_reason, provider_status_history audit table, and status transition security

-- 1. Add rejection_reason column to provider_profiles if not present
ALTER TABLE public.provider_profiles 
ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

-- 2. Create provider_status_history table for auditing status changes
CREATE TABLE IF NOT EXISTS public.provider_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT NOT NULL REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Index for fast lookup of history by provider_id
CREATE INDEX IF NOT EXISTS idx_provider_status_history_provider_id 
ON public.provider_status_history(provider_id);

-- 3. Enable RLS on provider_status_history
ALTER TABLE public.provider_status_history ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any to prevent conflicts
DROP POLICY IF EXISTS "Providers view own status history" ON public.provider_status_history;
DROP POLICY IF EXISTS "Providers insert status history" ON public.provider_status_history;

-- Providers can view history for their own profile
CREATE POLICY "Providers view own status history"
ON public.provider_status_history FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = public.provider_status_history.provider_id
    AND p.user_id = auth.uid()
  )
);

-- Providers can insert history records when changing status for their own profile
CREATE POLICY "Providers insert status history"
ON public.provider_status_history FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = public.provider_status_history.provider_id
    AND p.user_id = auth.uid()
  )
);

-- 4. Security on provider_profiles status updates for authenticated providers
-- Drop existing update policy if present
DROP POLICY IF EXISTS "Providers update own profile draft or request review" ON public.provider_profiles;

-- Allow providers to update their profile ONLY IF status remains 'draft' or transitions to 'pending_review'
-- Untrusted updates to 'published' or 'suspended' are blocked by RLS!
CREATE POLICY "Providers update own profile draft or request review"
ON public.provider_profiles FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = public.provider_profiles.profile_id
    AND p.user_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = public.provider_profiles.profile_id
    AND p.user_id = auth.uid()
  ) AND
  (status IN ('draft', 'pending_review'))
);
