-- Migration: 20260815_provider_analytics.sql
-- Description: Create provider_analytics_events table, security policies, performance indexes, and log_analytics_event RPC

-- 1. Create provider_analytics_events table
CREATE TABLE IF NOT EXISTS public.provider_analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id BIGINT REFERENCES public.provider_profiles(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('search', 'provider_impression', 'profile_view', 'contact_click', 'social_click', 'portfolio_view')),
  search_term TEXT,
  channel TEXT,
  portfolio_item_id BIGINT REFERENCES public.portfolio_items(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Performance Composite Indexes
CREATE INDEX IF NOT EXISTS idx_analytics_provider_date 
ON public.provider_analytics_events(provider_id, created_at, event_type);

CREATE INDEX IF NOT EXISTS idx_analytics_search_term 
ON public.provider_analytics_events(search_term) 
WHERE event_type = 'search';

-- 3. Enable Row Level Security
ALTER TABLE public.provider_analytics_events ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Providers and Admins view own analytics events" ON public.provider_analytics_events;

-- Allow Providers to view ONLY their own analytics events (and Admins)
CREATE POLICY "Providers and Admins view own analytics events"
ON public.provider_analytics_events FOR SELECT
TO authenticated
USING (
  public.is_admin(auth.uid()) OR
  (
    provider_id IS NOT NULL AND
    EXISTS (
      SELECT 1 FROM public.provider_profiles pp
      JOIN public.profiles p ON p.id = pp.profile_id
      WHERE pp.id = public.provider_analytics_events.provider_id
      AND p.user_id = auth.uid()
    )
  )
);

-- 4. RPC SECURITY DEFINER: log_analytics_event
-- Safely logs events for catalog visitors while filtering out owner self-views
CREATE OR REPLACE FUNCTION public.log_analytics_event(
  p_provider_id BIGINT DEFAULT NULL,
  p_event_type TEXT DEFAULT 'profile_view',
  p_search_term TEXT DEFAULT NULL,
  p_channel TEXT DEFAULT NULL,
  p_portfolio_item_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_owner_user_id UUID;
  v_current_user_id UUID;
BEGIN
  v_current_user_id := auth.uid();

  -- If provider_id is specified, check if current logged-in user is the provider owner
  IF p_provider_id IS NOT NULL AND v_current_user_id IS NOT NULL THEN
    SELECT p.user_id INTO v_owner_user_id
    FROM public.provider_profiles pp
    JOIN public.profiles p ON p.id = pp.profile_id
    WHERE pp.id = p_provider_id;

    -- Ignore self-views/self-actions by profile owner to prevent self-inflation
    IF v_owner_user_id IS NOT NULL AND v_owner_user_id = v_current_user_id THEN
      RETURN jsonb_build_object('success', true, 'ignored', true, 'reason', 'owner_self_view');
    END IF;
  END IF;

  -- Insert aggregate analytics event
  INSERT INTO public.provider_analytics_events (
    provider_id,
    event_type,
    search_term,
    channel,
    portfolio_item_id,
    created_at
  )
  VALUES (
    p_provider_id,
    p_event_type,
    NULLIF(trim(p_search_term), ''),
    NULLIF(trim(p_channel), ''),
    p_portfolio_item_id,
    timezone('utc'::text, now())
  );

  RETURN jsonb_build_object('success', true);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;
